services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    command: bash -c "bin/rails db:prepare && bin/rails s -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
      GEMINI_API_KEY: GEMINI_API_KEY_PLACEHOLDER
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /front
    command: sh -c "pnpm install && pnpm dev --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
      PNPM_HOME: /pnpm
    volumes:
      - ./front:/front:cached
      - node_modules:/front/node_modules
      # - pnpm-store:/pnpm

volumes:
  db_data:
  bundle_cache:
  node_modules:
