services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development # 変更箇所
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    ports:
      - "4000:3000"
    volumes:
      - ./api:/app
    command: bash -c "bin/rails db:prepare && bin/rails s -b 0.0.0.0 -p 3000"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: app_development
      RAILS_ENV: development
      GEMINI_API_KEY: GEMINI_API_KEY_PLACEHOLDER
      FRONT_OAUTH_UID: "Nea5B3HT2rapVdGQ9pHTFlc4Mh4q8uLAzbjF2UG5UPU"
    depends_on:
      db:
        condition: service_healthy

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /front
    command: sh -c "pnpm install && pnpm dev --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: http://localhost:4000
      PNPM_HOME: /pnpm
    volumes:
      - ./front:/front:cached
      - node_modules:/front/node_modules

volumes:
  db_data:
  bundle_cache:
  node_modules:
