default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
  host: <%= ENV.fetch("PGHOST", "db") %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE_TEST", "app_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE_PRODUCTION", "app_production") %>
  variables:
    statement_timeout: 5000
